# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Itlf94RGj22FgVVg98M7pkyfemcGo5k
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score

# Load your dataset (replace with your actual file)
data = pd.read_csv('traffic_accidents.csv')

# Display basic info
print(data.head())
print(data.isnull().sum())

# Drop or fill missing values
data = data.dropna()

# Feature selection (customize based on your dataset)
features = ['weather_condition', 'road_condition', 'light_condition', 'vehicle_count', 'hour']
target = 'accident_severity'

# Encode categorical variables
data_encoded = pd.get_dummies(data[features])
X = data_encoded
y = data[target]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model training